MULTIPLICADOR_ITERATION="$1"
MAX_IN_SOLUTION="$2"
FRAC_FIX="$3"
FRAC_SUB_FICA="$4"
MAX_POND="$5"


SEED=1
for INSTANCE in klsf_instances/*;
do
   echo "$INSTANCE"
   SEED=1
   while [ $SEED -lt 31 ];
   do 
      PART=0
         echo "./p $INSTANCE $SEED $MULTIPLICADOR_ITERATION $MAX_IN_SOLUTION $FRAC_FIX $FRAC_SUB_FICA $MAX_POND 1"
         ./p $INSTANCE $SEED $MULTIPLICADOR_ITERATION $MAX_IN_SOLUTION $FRAC_FIX $FRAC_SUB_FICA $MAX_POND 1
         let PART=PART+1;
      let SEED=SEED+1;
      echo "$SEED"
   done
done
      
